[versions]
activityKtx = "1.9.0"
agp = "8.5.0"
kotlin = "2.0.0"
soloader = "0.10.5"
yoga = "3.1.0"

[libraries]
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
soloader = { module = "com.facebook.soloader:soloader", version.ref = "soloader" }
yoga = { module = "com.facebook.yoga:yoga", version.ref = "yoga" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

